// Generated by tools/design/build-css.ts from .agent/design-mirror/_ds/.
// Do not edit by hand: run `node tools/design/emit.ts` and commit the result.
// The mirror holds the design project's files verbatim; the two edits made on
// the way here are marked in the CSS itself.

export const HA_DESIGN_SYSTEM_CSS = String.raw`
/* ===== _ds/tokens/fonts.css ===== */
/* Korean copy falls back to Noto Sans KR — Google Fonts is the only external
   origin an Ingress add-on UI is allowed to reach. Must stay above @font-face. */
/* removed by tools/design/build-css.ts: the Google Fonts @import — the page makes no external request */

/* Roboto — Google's variable TTF, copied from google/fonts (ofl/roboto, SIL OFL 1.1).
   HA ships per-weight woff2 for Roboto 100–900; one variable file covers the whole
   axis, which suits an add-on that should not depend on the network. */
/* removed by tools/design/build-css.ts: the Roboto @font-face — the variable TTF is not shipped with the add-on */

/* ===== _ds/tokens/core-colors.css ===== */
/* Core color ramps — verbatim from home-assistant/frontend
   src/resources/theme/color/core.globals.ts. Building blocks only:
   never reference these directly in components, use the semantic layer. */
:root{
--ha-color-black:#000000;
--ha-color-white:#ffffff;

--ha-color-primary-05:#001721;
--ha-color-primary-10:#002e3e;
--ha-color-primary-20:#004156;
--ha-color-primary-30:#006787;
--ha-color-primary-40:#009ac7;
--ha-color-primary-50:#18bcf2;
--ha-color-primary-60:#37c8fd;
--ha-color-primary-70:#7bd4fb;
--ha-color-primary-80:#b9e6fc;
--ha-color-primary-90:#dff3fc;
--ha-color-primary-95:#eff9fe;

--ha-color-neutral-05:#141414;
--ha-color-neutral-10:#202020;
--ha-color-neutral-20:#363636;
--ha-color-neutral-30:#4a4a4a;
--ha-color-neutral-40:#5e5e5e;
--ha-color-neutral-50:#7a7a7a;
--ha-color-neutral-60:#989898;
--ha-color-neutral-70:#b1b1b1;
--ha-color-neutral-80:#cccccc;
--ha-color-neutral-90:#e6e6e6;
--ha-color-neutral-95:#f3f3f3;

--ha-color-orange-05:#280700;
--ha-color-orange-10:#3b0f00;
--ha-color-orange-20:#5e1c00;
--ha-color-orange-30:#7e2900;
--ha-color-orange-40:#9d3800;
--ha-color-orange-50:#c94e00;
--ha-color-orange-60:#f36d00;
--ha-color-orange-70:#ff9342;
--ha-color-orange-80:#ffbb89;
--ha-color-orange-90:#ffe0c8;
--ha-color-orange-95:#fff0e4;

--ha-color-red-05:#2a040b;
--ha-color-red-10:#3e0913;
--ha-color-red-20:#631323;
--ha-color-red-30:#8a132c;
--ha-color-red-40:#b30532;
--ha-color-red-50:#dc3146;
--ha-color-red-60:#f3676c;
--ha-color-red-70:#fd8f90;
--ha-color-red-80:#ffb8b6;
--ha-color-red-90:#ffdedc;
--ha-color-red-95:#fff0ef;

--ha-color-green-05:#031608;
--ha-color-green-10:#052310;
--ha-color-green-20:#0a3a1d;
--ha-color-green-30:#0a5027;
--ha-color-green-40:#036730;
--ha-color-green-50:#00883c;
--ha-color-green-60:#00ac49;
--ha-color-green-70:#5dc36f;
--ha-color-green-80:#93da98;
--ha-color-green-90:#c2f2c1;
--ha-color-green-95:#e3f9e3;
}

/* ===== _ds/tokens/semantic-colors.css ===== */
/* Semantic colors — from src/resources/theme/color/semantic.globals.ts.
   The fill/border/on triads are the layer components should reference.
   Naming: fill-<intent>-<loudness>-<state>, on-<intent>-<loudness>. */
:root{
--ha-color-focus:var(--ha-color-neutral-60);

--ha-color-text-primary:var(--ha-color-neutral-05);
--ha-color-text-secondary:var(--ha-color-neutral-40);
--ha-color-text-disabled:var(--ha-color-neutral-60);
--ha-color-text-link:var(--ha-color-primary-40);
--ha-color-text-primary-inverted:var(--ha-color-white);
--ha-color-text-secondary-inverted:var(--ha-color-neutral-20);

--ha-color-border-primary-quiet:var(--ha-color-primary-90);
--ha-color-border-primary-normal:var(--ha-color-primary-70);
--ha-color-border-primary-loud:var(--ha-color-primary-40);
--ha-color-border-neutral-quiet:var(--ha-color-neutral-90);
--ha-color-border-neutral-normal:var(--ha-color-neutral-60);
--ha-color-border-neutral-loud:var(--ha-color-neutral-40);
--ha-color-border-danger-quiet:var(--ha-color-red-90);
--ha-color-border-danger-normal:var(--ha-color-red-70);
--ha-color-border-danger-loud:var(--ha-color-red-40);
--ha-color-border-warning-quiet:var(--ha-color-orange-90);
--ha-color-border-warning-normal:var(--ha-color-orange-70);
--ha-color-border-warning-loud:var(--ha-color-orange-40);
--ha-color-border-success-quiet:var(--ha-color-green-90);
--ha-color-border-success-normal:var(--ha-color-green-70);
--ha-color-border-success-loud:var(--ha-color-green-40);

--ha-color-fill-primary-quiet-resting:var(--ha-color-primary-95);
--ha-color-fill-primary-quiet-hover:var(--ha-color-primary-90);
--ha-color-fill-primary-normal-resting:var(--ha-color-primary-90);
--ha-color-fill-primary-normal-hover:var(--ha-color-primary-80);
--ha-color-fill-primary-loud-resting:var(--ha-color-primary-40);
--ha-color-fill-primary-loud-hover:var(--ha-color-primary-30);
--ha-color-fill-neutral-quiet-resting:var(--ha-color-neutral-95);
--ha-color-fill-neutral-quiet-hover:var(--ha-color-neutral-90);
--ha-color-fill-neutral-normal-resting:var(--ha-color-neutral-90);
--ha-color-fill-neutral-normal-hover:var(--ha-color-neutral-80);
--ha-color-fill-neutral-loud-resting:var(--ha-color-neutral-40);
--ha-color-fill-neutral-loud-hover:var(--ha-color-neutral-30);
--ha-color-fill-disabled-quiet-resting:var(--ha-color-neutral-95);
--ha-color-fill-disabled-normal-resting:var(--ha-color-neutral-95);
--ha-color-fill-disabled-loud-resting:var(--ha-color-neutral-80);
--ha-color-fill-danger-quiet-resting:var(--ha-color-red-95);
--ha-color-fill-danger-quiet-hover:var(--ha-color-red-90);
--ha-color-fill-danger-normal-resting:var(--ha-color-red-90);
--ha-color-fill-danger-normal-hover:var(--ha-color-red-80);
--ha-color-fill-danger-loud-resting:var(--ha-color-red-50);
--ha-color-fill-danger-loud-hover:var(--ha-color-red-40);
--ha-color-fill-warning-quiet-resting:var(--ha-color-orange-95);
--ha-color-fill-warning-quiet-hover:var(--ha-color-orange-90);
--ha-color-fill-warning-normal-resting:var(--ha-color-orange-90);
--ha-color-fill-warning-normal-hover:var(--ha-color-orange-80);
--ha-color-fill-warning-loud-resting:var(--ha-color-orange-70);
--ha-color-fill-warning-loud-hover:var(--ha-color-orange-50);
--ha-color-fill-success-quiet-resting:var(--ha-color-green-95);
--ha-color-fill-success-quiet-hover:var(--ha-color-green-90);
--ha-color-fill-success-normal-resting:var(--ha-color-green-90);
--ha-color-fill-success-normal-hover:var(--ha-color-green-80);
--ha-color-fill-success-loud-resting:var(--ha-color-green-50);
--ha-color-fill-success-loud-hover:var(--ha-color-green-40);

--ha-color-on-primary-quiet:var(--ha-color-primary-50);
--ha-color-on-primary-normal:var(--ha-color-primary-40);
--ha-color-on-primary-loud:var(--ha-color-white);
--ha-color-on-neutral-quiet:var(--ha-color-neutral-50);
--ha-color-on-neutral-normal:var(--ha-color-neutral-40);
--ha-color-on-neutral-loud:var(--ha-color-white);
--ha-color-on-disabled-quiet:var(--ha-color-neutral-80);
--ha-color-on-disabled-normal:var(--ha-color-neutral-70);
--ha-color-on-disabled-loud:var(--ha-color-neutral-95);
--ha-color-on-danger-quiet:var(--ha-color-red-50);
--ha-color-on-danger-normal:var(--ha-color-red-40);
--ha-color-on-danger-loud:var(--ha-color-white);
--ha-color-on-warning-quiet:var(--ha-color-orange-50);
--ha-color-on-warning-normal:var(--ha-color-orange-40);
--ha-color-on-warning-loud:var(--ha-color-white);
--ha-color-on-success-quiet:var(--ha-color-green-50);
--ha-color-on-success-normal:var(--ha-color-green-40);
--ha-color-on-success-loud:var(--ha-color-white);

--ha-color-surface-default:var(--ha-color-white);
--ha-color-surface-low:var(--ha-color-neutral-95);
--ha-color-surface-lower:var(--ha-color-neutral-90);
--ha-color-on-surface-default:var(--ha-color-neutral-05);

--ha-color-form-background:var(--ha-color-neutral-95);
--ha-color-form-background-hover:var(--ha-color-neutral-90);
--ha-color-form-background-disabled:var(--ha-color-neutral-80);
--ha-color-shadow-scrollable-fade:rgba(0,0,0,0.08);
}
@media (prefers-color-scheme:dark){:root{
--ha-color-text-primary:var(--ha-color-white);
--ha-color-text-secondary:var(--ha-color-neutral-80);
--ha-color-text-link:var(--ha-color-primary-60);
--ha-color-text-primary-inverted:var(--ha-color-black);
--ha-color-text-secondary-inverted:var(--ha-color-neutral-40);

--ha-color-border-neutral-quiet:var(--ha-color-neutral-40);
--ha-color-border-neutral-normal:var(--ha-color-neutral-50);
--ha-color-border-neutral-loud:var(--ha-color-neutral-70);
--ha-color-border-danger-normal:var(--ha-color-red-50);
--ha-color-border-danger-loud:var(--ha-color-red-50);
--ha-color-border-warning-normal:var(--ha-color-orange-50);
--ha-color-border-warning-loud:var(--ha-color-orange-50);

--ha-color-fill-primary-quiet-resting:var(--ha-color-primary-05);
--ha-color-fill-primary-quiet-hover:var(--ha-color-primary-10);
--ha-color-fill-primary-normal-resting:var(--ha-color-primary-10);
--ha-color-fill-primary-normal-hover:var(--ha-color-primary-20);
--ha-color-fill-neutral-quiet-resting:var(--ha-color-neutral-05);
--ha-color-fill-neutral-quiet-hover:var(--ha-color-neutral-10);
--ha-color-fill-neutral-normal-resting:var(--ha-color-neutral-10);
--ha-color-fill-neutral-normal-hover:var(--ha-color-neutral-20);
--ha-color-fill-neutral-loud-resting:var(--ha-color-neutral-60);
--ha-color-fill-neutral-loud-hover:var(--ha-color-neutral-70);
--ha-color-fill-disabled-quiet-resting:var(--ha-color-neutral-10);
--ha-color-fill-disabled-normal-resting:var(--ha-color-neutral-20);
--ha-color-fill-disabled-loud-resting:var(--ha-color-neutral-30);
--ha-color-fill-danger-quiet-resting:var(--ha-color-red-05);
--ha-color-fill-danger-quiet-hover:var(--ha-color-red-10);
--ha-color-fill-danger-normal-resting:var(--ha-color-red-10);
--ha-color-fill-danger-normal-hover:var(--ha-color-red-20);
--ha-color-fill-danger-loud-resting:var(--ha-color-red-40);
--ha-color-fill-danger-loud-hover:var(--ha-color-red-30);
--ha-color-fill-warning-quiet-resting:var(--ha-color-orange-05);
--ha-color-fill-warning-quiet-hover:var(--ha-color-orange-10);
--ha-color-fill-warning-normal-resting:var(--ha-color-orange-10);
--ha-color-fill-warning-normal-hover:var(--ha-color-orange-20);
--ha-color-fill-warning-loud-resting:var(--ha-color-orange-40);
--ha-color-fill-warning-loud-hover:var(--ha-color-orange-30);
--ha-color-fill-success-quiet-resting:var(--ha-color-green-05);
--ha-color-fill-success-quiet-hover:var(--ha-color-green-10);
--ha-color-fill-success-normal-resting:var(--ha-color-green-10);
--ha-color-fill-success-normal-hover:var(--ha-color-green-20);
--ha-color-fill-success-loud-resting:var(--ha-color-green-40);
--ha-color-fill-success-loud-hover:var(--ha-color-green-30);

--ha-color-on-primary-quiet:var(--ha-color-primary-70);
--ha-color-on-primary-normal:var(--ha-color-primary-60);
--ha-color-on-neutral-quiet:var(--ha-color-neutral-70);
--ha-color-on-neutral-normal:var(--ha-color-neutral-60);
--ha-color-on-disabled-quiet:var(--ha-color-neutral-40);
--ha-color-on-disabled-normal:var(--ha-color-neutral-50);
--ha-color-on-disabled-loud:var(--ha-color-neutral-50);
--ha-color-on-danger-quiet:var(--ha-color-red-70);
--ha-color-on-danger-normal:var(--ha-color-red-60);
--ha-color-on-warning-quiet:var(--ha-color-orange-70);
--ha-color-on-warning-normal:var(--ha-color-orange-60);
--ha-color-on-success-quiet:var(--ha-color-green-70);
--ha-color-on-success-normal:var(--ha-color-green-60);

--ha-color-surface-default:var(--ha-color-neutral-10);
--ha-color-surface-low:var(--ha-color-neutral-05);
--ha-color-surface-lower:var(--ha-color-black);
--ha-color-on-surface-default:var(--ha-color-neutral-95);

--ha-color-form-background:var(--ha-color-neutral-20);
--ha-color-form-background-hover:var(--ha-color-neutral-30);
--ha-color-form-background-disabled:var(--ha-color-neutral-20);
}}

/* ===== _ds/tokens/theme.css ===== */
/* Theme aliases — the names components and dashboards actually consume.
   From src/resources/theme/color/color.globals.ts (colorStyles + darkColorStyles).
   Light is the default; dark switches on prefers-color-scheme because an Ingress
   iframe does NOT inherit the HA theme variables from the parent frontend. */
:root{
/* text */
--primary-text-color:var(--ha-color-text-primary);
--secondary-text-color:var(--ha-color-text-secondary);
--text-primary-color:#ffffff;
--text-light-primary-color:#212121;
--disabled-text-color:#bdbdbd;

/* brand */
--primary-color:var(--ha-color-primary-40);
--dark-primary-color:#0288d1;
--darker-primary-color:#016194;
--light-primary-color:#b3e5fc;
--accent-color:#ff9800;

/* lines and shadows */
--divider-color:rgba(0,0,0,0.12);
--outline-color:rgba(0,0,0,0.12);
--outline-hover-color:rgba(0,0,0,0.24);
--shadow-color:rgba(0,0,0,0.16);
--scrollbar-thumb-color:rgb(194,194,194);

/* rgb channels, for rgba() composition */
--rgb-primary-color:0,154,199;
--rgb-accent-color:255,152,0;
--rgb-primary-text-color:33,33,33;
--rgb-secondary-text-color:114,114,114;
--rgb-text-primary-color:255,255,255;
--rgb-card-background-color:255,255,255;
--rgb-warning-color:255,166,0;
--rgb-error-color:219,68,55;
--rgb-success-color:67,160,71;
--rgb-info-color:3,155,229;

/* status */
--error-color:#db4437;
--warning-color:#ffa600;
--success-color:#43a047;
--info-color:#039be5;

/* backgrounds */
--card-background-color:#ffffff;
--primary-background-color:#fafafa;
--secondary-background-color:#e5e5e5;
--clear-background-color:#ffffff;

/* palette */
--disabled-color:#bdbdbd;
--red-color:#f44336;
--pink-color:#e91e63;
--purple-color:#926bc7;
--deep-purple-color:#6e41ab;
--indigo-color:#3f51b5;
--blue-color:#2196f3;
--light-blue-color:#03a9f4;
--cyan-color:#00bcd4;
--teal-color:#009688;
--green-color:#4caf50;
--light-green-color:#8bc34a;
--lime-color:#cddc39;
--yellow-color:#ffeb3b;
--amber-color:#ffc107;
--orange-color:#ff9800;
--deep-orange-color:#ff6f22;
--brown-color:#795548;
--light-grey-color:#bdbdbd;
--grey-color:#9e9e9e;
--dark-grey-color:#606060;
--blue-grey-color:#607d8b;
--black-color:#000000;
--white-color:#ffffff;

/* entity state colors */
--state-icon-color:#44739e;
--state-active-color:var(--amber-color);
--state-inactive-color:var(--grey-color);
--state-unavailable-color:var(--disabled-text-color);
--state-light-active-color:var(--amber-color);
--state-switch-active-color:var(--amber-color);
--state-binary_sensor-active-color:var(--amber-color);
--state-climate-heat-color:var(--deep-orange-color);
--state-climate-cool-color:var(--blue-color);
--state-climate-auto-color:var(--green-color);
--state-climate-dry-color:var(--orange-color);
--state-climate-fan_only-color:var(--cyan-color);
--state-climate-heat-cool-color:var(--amber-color);
--state-fan-active-color:var(--cyan-color);
--state-cover-active-color:var(--purple-color);
--state-lock-locked-color:var(--green-color);
--state-lock-unlocked-color:var(--red-color);
--state-lock-jammed-color:var(--red-color);
--state-media_player-active-color:var(--light-blue-color);
--state-person-home-color:var(--green-color);
--state-vacuum-active-color:var(--teal-color);
--state-update-active-color:var(--orange-color);
--state-sun-above_horizon-color:var(--amber-color);
--state-sun-below_horizon-color:var(--indigo-color);
--state-alarm_control_panel-armed_home-color:var(--green-color);
--state-alarm_control_panel-triggered-color:var(--red-color);
--state-sensor-battery-high-color:var(--green-color);
--state-sensor-battery-medium-color:var(--orange-color);
--state-sensor-battery-low-color:var(--red-color);

/* energy dashboard */
--energy-grid-consumption-color:#488fc2;
--energy-grid-return-color:#8353d1;
--energy-solar-color:#ff9800;
--energy-non-fossil-color:#0f9d58;
--energy-battery-out-color:#4db6ac;
--energy-battery-in-color:#f06292;
--energy-gas-color:#8e021b;
--energy-water-color:#00bcd4;

/* graph series */
--color-1:#4269d0;--color-2:#f4bd4a;--color-3:#ff725c;--color-4:#6cc5b0;--color-5:#a463f2;
--color-6:#ff8ab7;--color-7:#9c6b4e;--color-8:#97bbf5;--color-9:#01ab63;--color-10:#094bad;

/* inputs */
--input-idle-line-color:rgba(0,0,0,0.42);
--input-hover-line-color:rgba(0,0,0,0.87);
--input-disabled-line-color:rgba(0,0,0,0.06);
--input-outlined-idle-border-color:rgba(0,0,0,0.38);
--input-outlined-hover-border-color:rgba(0,0,0,0.87);
--input-fill-color:rgb(245,245,245);
--input-disabled-fill-color:rgb(250,250,250);
--input-ink-color:rgba(0,0,0,0.87);
--input-label-ink-color:rgba(0,0,0,0.6);
--input-disabled-ink-color:rgba(0,0,0,0.37);
--input-dropdown-icon-color:rgba(0,0,0,0.54);

/* derived surfaces */
--sidebar-text-color:var(--primary-text-color);
--sidebar-background-color:var(--card-background-color);
--sidebar-selected-text-color:var(--primary-color);
--sidebar-icon-color:rgba(var(--rgb-primary-text-color),0.6);
--slider-color:var(--primary-color);
--slider-secondary-color:var(--light-primary-color);
--slider-track-color:var(--scrollbar-thumb-color);
--table-header-background-color:var(--input-fill-color);
--table-row-background-color:var(--primary-background-color);
--table-row-alternative-background-color:var(--secondary-background-color);
--markdown-code-background-color:var(--primary-background-color);
--app-header-background-color:var(--sidebar-background-color);
--app-header-text-color:var(--sidebar-text-color);
--app-header-border-bottom:1px solid var(--divider-color);
--chip-background-color:rgba(var(--rgb-primary-text-color),0.15);
--ha-assist-chip-filled-container-color:rgba(var(--rgb-primary-text-color),0.15);
--ha-assist-chip-active-container-color:rgba(var(--rgb-primary-color),0.15);

/* ha-card defaults: flat surface, 1px border, 12px radius */
--ha-card-background:var(--card-background-color);
--ha-card-border-radius:var(--ha-border-radius-lg);
--ha-card-border-width:1px;
--ha-card-border-color:var(--divider-color);
--ha-card-box-shadow:none;
}
@media (prefers-color-scheme:dark){:root{
--primary-background-color:#111111;
--card-background-color:#1c1c1c;
--secondary-background-color:#282828;
--clear-background-color:#111111;
--primary-text-color:#e1e1e1;
--secondary-text-color:#9b9b9b;
--disabled-text-color:#6f6f6f;
--divider-color:rgba(225,225,225,0.12);
--outline-color:rgba(225,225,225,0.12);
--outline-hover-color:rgba(225,225,225,0.24);
--shadow-color:rgba(0,0,0,0.48);
--scrollbar-thumb-color:rgb(110,110,110);
--disabled-color:#464646;
--rgb-primary-text-color:225,225,225;
--rgb-card-background-color:28,28,28;
--energy-grid-return-color:#a280db;
--input-idle-line-color:rgba(255,255,255,0.42);
--input-hover-line-color:rgba(255,255,255,0.87);
--input-disabled-line-color:rgba(255,255,255,0.06);
--input-outlined-idle-border-color:rgba(255,255,255,0.38);
--input-outlined-hover-border-color:rgba(255,255,255,0.87);
--input-fill-color:rgba(255,255,255,0.05);
--input-disabled-fill-color:rgba(255,255,255,0.02);
--input-ink-color:rgba(255,255,255,0.87);
--input-label-ink-color:rgba(255,255,255,0.6);
--input-disabled-ink-color:rgba(255,255,255,0.37);
--input-dropdown-icon-color:rgba(255,255,255,0.54);
--map-filter:invert(0.9) hue-rotate(170deg) brightness(1.5) contrast(1.2) saturate(0.3); /* @kind other */
}}

/* ===== _ds/tokens/typography.css ===== */
/* Typography — from src/resources/theme/typography.globals.ts.
   Root font-size is 14px in HA, so 1rem = 14px. Sizes are declared in px
   through --ha-font-size-scale so an Ingress UI can be scaled as a whole. */
:root{
--ha-font-family-body:Roboto,"Noto Sans KR","Apple SD Gothic Neo","Malgun Gothic",system-ui,sans-serif;
--ha-font-family-heading:var(--ha-font-family-body);
--ha-font-family-code:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;
--ha-font-family-longform:ui-sans-serif,system-ui,sans-serif;

--ha-font-size-scale:1;
--ha-font-size-xs:calc(10px * var(--ha-font-size-scale));
--ha-font-size-s:calc(12px * var(--ha-font-size-scale));
--ha-font-size-m:calc(14px * var(--ha-font-size-scale));
--ha-font-size-l:calc(16px * var(--ha-font-size-scale));
--ha-font-size-xl:calc(20px * var(--ha-font-size-scale));
--ha-font-size-2xl:calc(24px * var(--ha-font-size-scale));
--ha-font-size-3xl:calc(28px * var(--ha-font-size-scale));
--ha-font-size-4xl:calc(32px * var(--ha-font-size-scale));
--ha-font-size-5xl:calc(40px * var(--ha-font-size-scale));

--ha-font-weight-light:300;
--ha-font-weight-normal:400;
--ha-font-weight-medium:500;
--ha-font-weight-bold:700;
--ha-font-weight-body:var(--ha-font-weight-normal);
--ha-font-weight-heading:var(--ha-font-weight-bold);
--ha-font-weight-action:var(--ha-font-weight-medium);

--ha-line-height-condensed:1.2;
--ha-line-height-normal:1.6;
--ha-line-height-expanded:2;

--ha-font-smoothing:antialiased;
--ha-moz-osx-font-smoothing:grayscale;
}
html{font-size:14px}
body{font-family:var(--ha-font-family-body);font-size:var(--ha-font-size-m);font-weight:var(--ha-font-weight-normal);line-height:var(--ha-line-height-normal);-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}

/* ===== _ds/tokens/core.css ===== */
/* Radius, border width, spacing scale, motion durations —
   from src/resources/theme/core.globals.ts. */
:root{
--ha-border-width-sm:1px;
--ha-border-width-md:2px;
--ha-border-width-lg:3px;

--ha-border-radius-sm:4px;
--ha-border-radius-md:8px;
--ha-border-radius-lg:12px;
--ha-border-radius-xl:16px;
--ha-border-radius-2xl:20px;
--ha-border-radius-3xl:24px;
--ha-border-radius-4xl:28px;
--ha-border-radius-5xl:32px;
--ha-border-radius-6xl:36px;
--ha-border-radius-pill:9999px;
--ha-border-radius-circle:50%;
--ha-border-radius-square:0;

--ha-space-1:4px;
--ha-space-2:8px;
--ha-space-3:12px;
--ha-space-4:16px;
--ha-space-5:20px;
--ha-space-6:24px;
--ha-space-7:28px;
--ha-space-8:32px;
--ha-space-9:36px;
--ha-space-10:40px;
--ha-space-11:44px;
--ha-space-12:48px;
--ha-space-13:52px;
--ha-space-14:56px;
--ha-space-15:60px;
--ha-space-16:64px;
--ha-space-17:68px;
--ha-space-18:72px;
--ha-space-19:76px;
--ha-space-20:80px;

--ha-animation-duration-none:1ms; /* @kind other */
--ha-animation-duration-instant:75ms; /* @kind other */
--ha-animation-duration-fast:150ms; /* @kind other */
--ha-animation-duration-normal:250ms; /* @kind other */
--ha-animation-duration-slow:350ms; /* @kind other */

/* Interaction timings used by the ha-control-* family */
--ha-control-transition:180ms ease-in-out; /* @kind other */
--ha-expansion-transition:300ms cubic-bezier(0.4,0,0.2,1); /* @kind other */
--ha-card-transition:0.3s ease-out; /* @kind other */

/* Layout constants */
--header-height:56px;
--row-height:56px;
--column-gap:32px;
--narrow-column-gap:8px;
--column-max-width:500px;
--control-height:48px;
--min-touch-target:44px;
}
@media (prefers-reduced-motion:reduce){:root{--ha-animation-duration-instant:1ms; /* @kind other */ --ha-animation-duration-fast:1ms; /* @kind other */ --ha-animation-duration-normal:1ms; /* @kind other */ --ha-animation-duration-slow:1ms /* @kind other */}}

/* ===== _ds/tokens/components.css ===== */
/* Component-level knobs. Every ha-* component reads these, so a consumer can
   retheme a whole family without touching component CSS. Names match upstream
   (--control-switch-on-color, --tile-color, …) so values set on any ancestor
   in a Home Assistant dashboard keep working. */
:root{
/* tile card */
--tile-color:var(--state-inactive-color);
--tile-icon-size:36px;
--tile-icon-opacity:0.2; /* @kind other */
--tile-icon-hover-opacity:0.35; /* @kind other */
--tile-badge-background-color:var(--primary-color);

/* control button */
--control-button-background-color:var(--disabled-color);
--control-button-background-opacity:0.2; /* @kind other */
--control-button-active-color:var(--primary-color);
--control-button-icon-color:var(--primary-text-color);
--control-button-focus-color:var(--secondary-text-color);
--control-button-border-radius:var(--ha-border-radius-md);
--control-button-padding:8px;
--control-button-group-spacing:12px;
--control-button-group-thickness:40px;

/* control switch */
--control-switch-on-color:var(--primary-color);
--control-switch-off-color:var(--disabled-color);
--control-switch-background-opacity:0.2; /* @kind other */
--control-switch-hover-background-opacity:0.4; /* @kind other */
--control-switch-thickness:40px;
--control-switch-padding:4px;
--control-switch-border-radius:var(--ha-border-radius-lg);

/* control slider */
--control-slider-color:var(--primary-color);
--control-slider-background:var(--disabled-color);
--control-slider-background-opacity:0.2; /* @kind other */
--control-slider-thickness:40px;
--control-slider-border-radius:var(--ha-border-radius-md);
--ha-slider-handle-size:4px;
--ha-slider-handle-margin:calc(var(--control-slider-thickness) / 8);

/* circular slider */
--control-circular-slider-color:var(--primary-color);
--control-circular-slider-background:var(--disabled-color);
--control-circular-slider-background-opacity:0.3; /* @kind other */

/* number buttons */
--control-number-buttons-background-color:var(--disabled-color);
--control-number-buttons-background-opacity:0.2; /* @kind other */
--control-number-buttons-border-radius:var(--ha-border-radius-md);
--control-number-buttons-focus-color:var(--secondary-text-color);
--feature-height:40px;

/* control select */
--control-select-color:var(--primary-color);
--control-select-background:var(--disabled-color);
--control-select-background-opacity:0.2; /* @kind other */
--control-select-focused-opacity:0.2; /* @kind other */
--control-select-thickness:40px;
--control-select-stacked-thickness:56px;
--control-select-border-radius:10px;
--control-select-padding:4px;

/* badge, gauge, bar, dialog */
--badge-color:var(--secondary-text-color);
--ha-badge-size:36px;
--ha-alert-icon-size:24px;
--gauge-color:var(--primary-color);
--ha-bar-border-radius:var(--ha-border-radius-sm);
--ha-assist-chip-container-shape:16px;
--ha-dialog-border-radius:var(--ha-border-radius-4xl);
--expansion-panel-summary-padding:0 var(--ha-space-2);
--expansion-panel-content-padding:0 var(--ha-space-2);
}

/* ===== _ds/tokens/elevation.css ===== */
/* Shadows — from src/resources/theme/semantic.globals.ts.
   HA dashboards are flat by default: ha-card ships box-shadow:none and uses a
   1px border instead. These are for raised surfaces (dialogs, menus, tooltips). */
:root{
--ha-box-shadow-s:0 1px 2px 0 rgba(0,0,0,0.08),0 1px 3px 0 rgba(0,0,0,0.12);
--ha-box-shadow-m:0 3px 6px -1px rgba(0,0,0,0.1),0 8px 16px -2px rgba(0,0,0,0.15);
--ha-box-shadow-l:0 6px 12px -3px rgba(0,0,0,0.12),0 16px 32px -6px rgba(0,0,0,0.2);
--ha-card-raised-box-shadow:0px 2px 1px -1px rgba(0,0,0,0.2),0px 1px 1px 0px rgba(0,0,0,0.14),0px 1px 3px 0px rgba(0,0,0,0.12);
--bar-box-shadow:0 2px 12px var(--shadow-color);
--ha-dialog-scrim-backdrop-filter:brightness(68%); /* @kind other */
}
@media (prefers-color-scheme:dark){:root{
--ha-box-shadow-s:0 1px 2px 0 rgba(0,0,0,0.4),0 1px 3px 0 rgba(0,0,0,0.5);
--ha-box-shadow-m:0 3px 6px -1px rgba(0,0,0,0.35),0 8px 16px -2px rgba(0,0,0,0.45);
--ha-box-shadow-l:0 6px 12px -3px rgba(0,0,0,0.4),0 16px 32px -6px rgba(0,0,0,0.55);
}}

/* ===== _ds/components/ha-components.css ===== */
/* Component styles for the Home Assistant Design System.
   Every rule mirrors the geometry of its ha-* Lit source in
   home-assistant/frontend; the React components in components/ render these
   class names. Custom properties keep the same names as upstream so a value
   set on an ancestor (--control-switch-on-color, --tile-color, …) still works. */

/* ---------- ha-card / hui-tile-card ---------- */
.ha-card{position:relative;display:block;box-sizing:border-box;background:var(--ha-card-background,var(--card-background-color));color:var(--primary-text-color);border-radius:var(--ha-card-border-radius,var(--ha-border-radius-lg));border:var(--ha-card-border-width,1px) solid var(--ha-card-border-color,var(--divider-color));box-shadow:var(--ha-card-box-shadow,none);transition:all var(--ha-card-transition)}
.ha-card--raised{border:none;box-shadow:var(--ha-card-raised-box-shadow)}
.ha-card__header{display:block;margin:0;padding:var(--ha-space-3) var(--ha-space-4) var(--ha-space-4);color:var(--ha-card-header-color,var(--primary-text-color));font-size:var(--ha-font-size-2xl);font-weight:var(--ha-font-weight-normal);letter-spacing:-0.012em;line-height:var(--ha-line-height-expanded)}
.ha-card__content{padding:var(--ha-space-4)}
.ha-card__header+.ha-card__content{padding-top:0;margin-top:calc(var(--ha-space-2) * -1)}
.ha-card__actions{display:flex;gap:var(--ha-space-2);border-top:1px solid var(--divider-color);padding:var(--ha-space-2)}

.ha-tile{display:flex;flex-direction:column;height:100%;padding:0;cursor:pointer;text-align:start;font:inherit;border-color:var(--ha-card-border-color,var(--divider-color));transition:box-shadow var(--ha-control-transition),border-color var(--ha-control-transition)}
.ha-tile:hover{background:color-mix(in srgb,var(--tile-color) 4%,var(--card-background-color))}
.ha-tile:active{background:color-mix(in srgb,var(--tile-color) 12%,var(--card-background-color))}
.ha-tile:focus-visible{outline:none;border-color:var(--tile-color);box-shadow:0 0 0 1px var(--tile-color)}
.ha-tile__row{display:flex;flex-direction:column;flex:1;min-width:0}
.ha-tile__content{display:flex;flex-direction:row;align-items:center;gap:10px;padding:0 10px;min-height:var(--row-height,56px);flex:1;min-width:0;box-sizing:border-box}
.ha-tile__content--vertical{flex-direction:column;justify-content:center;text-align:center;padding:10px var(--ha-space-2);gap:2px}
.ha-tile__icon{position:relative;display:flex;align-items:center;justify-content:center;width:var(--tile-icon-size,36px);height:var(--tile-icon-size,36px);border-radius:var(--ha-tile-icon-border-radius,var(--ha-border-radius-pill));overflow:hidden;color:var(--tile-color);flex:none;transition:transform var(--ha-control-transition)}
.ha-tile__icon::before{content:"";position:absolute;inset:0;background-color:var(--tile-color);opacity:var(--tile-icon-opacity,0.2);transition:background-color var(--ha-control-transition),opacity var(--ha-control-transition)}
.ha-tile__icon>*{position:relative}
.ha-tile__icon:hover::before{opacity:var(--tile-icon-hover-opacity)}
.ha-tile__icon:active{transform:scale(1.2)}
.ha-tile__info{display:flex;flex-direction:column;align-items:flex-start;justify-content:center;width:100%;min-width:0}
.ha-tile__primary{width:100%;font-size:var(--ha-font-size-m);font-weight:var(--ha-font-weight-medium);line-height:var(--ha-line-height-normal);letter-spacing:0.1px;color:var(--primary-text-color);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.ha-tile__secondary{width:100%;font-size:var(--ha-font-size-s);font-weight:var(--ha-font-weight-normal);line-height:var(--ha-line-height-condensed);letter-spacing:0.4px;color:var(--primary-text-color);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.ha-tile__badge{position:absolute;top:3px;right:3px;display:flex;align-items:center;justify-content:center;width:16px;height:16px;border-radius:var(--ha-border-radius-md);background-color:var(--tile-badge-background-color,var(--primary-color));color:var(--white-color);line-height:0;transition:background-color 280ms ease-in-out}
.ha-tile__features{display:flex;gap:var(--ha-space-2);padding:0 var(--ha-space-3) var(--ha-space-3)}

/* ---------- ha-control-button ---------- */
.ha-control-button{position:relative;display:flex;flex-direction:row;align-items:center;justify-content:center;gap:var(--ha-space-2);width:40px;height:40px;padding:var(--control-button-padding,8px);box-sizing:border-box;margin:0;border:none;background:none;overflow:hidden;cursor:pointer;z-index:0;outline:none;text-align:center;font-family:var(--ha-font-family-body);font-size:inherit;font-weight:var(--ha-font-weight-medium);line-height:inherit;color:var(--control-button-icon-color,var(--primary-text-color));border-radius:var(--control-button-border-radius,var(--ha-border-radius-md));transition:box-shadow var(--ha-control-transition),color var(--ha-control-transition);-webkit-tap-highlight-color:transparent}
.ha-control-button::before{content:"";position:absolute;inset:0;background-color:var(--control-button-background-color,var(--disabled-color));opacity:var(--control-button-background-opacity,0.2);pointer-events:none;transition:background-color var(--ha-control-transition),opacity var(--ha-control-transition)}
.ha-control-button>*{position:relative;pointer-events:none;opacity:0.95}
.ha-control-button:hover::before{opacity:0.3}
.ha-control-button:active::before{opacity:0.4}
.ha-control-button:focus-visible{box-shadow:0 0 0 2px var(--control-button-focus-color,var(--secondary-text-color))}
.ha-control-button--wide{width:100%}
.ha-control-button--active{color:var(--white-color)}
.ha-control-button--active::before,.ha-control-button--active:hover::before,.ha-control-button--active:active::before{background-color:var(--control-button-active-color);opacity:1}
.ha-control-button--active:focus-visible{box-shadow:0 0 0 2px var(--control-button-active-color)}
.ha-control-button:disabled{cursor:not-allowed;color:var(--disabled-text-color)}
.ha-control-button:disabled::before{background-color:var(--disabled-color);opacity:0.2}
.ha-control-button-group{display:flex;flex-direction:row;gap:var(--control-button-group-spacing,12px);height:var(--control-button-group-thickness,40px)}
.ha-control-button-group>*{flex:1;width:100%;height:100%}
.ha-control-button-group--vertical{flex-direction:column;width:var(--control-button-group-thickness,40px);height:auto}

/* ---------- ha-control-switch ---------- */
.ha-control-switch{position:relative;display:flex;box-sizing:border-box;width:100%;height:var(--control-switch-thickness,40px);padding:var(--control-switch-padding,4px);border:none;background:none;border-radius:var(--control-switch-border-radius,var(--ha-border-radius-lg));cursor:pointer;outline:none;user-select:none;transition:box-shadow var(--ha-control-transition);-webkit-tap-highlight-color:transparent}
.ha-control-switch__background{position:absolute;inset:0;border-radius:inherit;background-color:var(--control-switch-off-color,var(--disabled-color));opacity:var(--control-switch-background-opacity,0.2);transition:background-color var(--ha-control-transition),opacity var(--ha-control-transition)}
.ha-control-switch:hover .ha-control-switch__background{opacity:var(--control-switch-hover-background-opacity,0.4)}
.ha-control-switch__button{position:relative;display:flex;align-items:center;justify-content:center;width:50%;height:100%;color:var(--white-color);background-color:var(--control-switch-off-color,var(--disabled-color));border-radius:calc(var(--control-switch-border-radius,var(--ha-border-radius-lg)) - var(--control-switch-padding,4px));transition:transform var(--ha-control-transition),background-color var(--ha-control-transition)}
.ha-control-switch--checked .ha-control-switch__background{background-color:var(--control-switch-on-color,var(--primary-color))}
.ha-control-switch--checked .ha-control-switch__button{transform:translateX(100%);background-color:var(--control-switch-on-color,var(--primary-color))}
.ha-control-switch:focus-visible{box-shadow:0 0 0 2px var(--control-switch-off-color,var(--disabled-color))}
.ha-control-switch--checked:focus-visible{box-shadow:0 0 0 2px var(--control-switch-on-color,var(--primary-color))}
.ha-control-switch:disabled{opacity:0.5;cursor:not-allowed}
.ha-control-switch--vertical{flex-direction:column;width:var(--control-switch-thickness,40px);height:100%}
.ha-control-switch--vertical .ha-control-switch__button{width:100%;height:50%}
.ha-control-switch--vertical.ha-control-switch--checked .ha-control-switch__button{transform:translateY(100%)}

/* ---------- ha-control-slider ---------- */
.ha-control-slider{position:relative;width:100%;height:var(--control-slider-thickness,40px)}
.ha-control-slider__track{position:relative;width:100%;height:100%;border-radius:var(--control-slider-border-radius,var(--ha-border-radius-md));overflow:hidden;cursor:pointer;outline:none;transition:box-shadow var(--ha-control-transition)}
.ha-control-slider__track:focus-visible{box-shadow:0 0 0 2px var(--control-slider-color,var(--primary-color))}
.ha-control-slider__background{position:absolute;inset:0;background:var(--control-slider-background,var(--disabled-color));opacity:var(--control-slider-background-opacity,0.2)}
.ha-control-slider__bar{position:absolute;top:0;left:0;width:100%;height:100%;background-color:var(--control-slider-color,var(--primary-color));border-radius:min(var(--control-slider-border-radius,var(--ha-border-radius-md)),var(--ha-border-radius-md));transform:translate3d(calc((var(--value,0) - 1) * 100%),0,0);transition:transform var(--ha-control-transition),background-color var(--ha-control-transition);pointer-events:none}
.ha-control-slider--handle .ha-control-slider__bar{transform:translate3d(calc((var(--value,0) - 1) * (100% - 2 * var(--ha-slider-handle-margin) - var(--ha-slider-handle-size))),0,0)}
.ha-control-slider--handle .ha-control-slider__bar::after{content:"";position:absolute;top:0;bottom:0;right:var(--ha-slider-handle-margin);margin:auto;height:50%;width:var(--ha-slider-handle-size);border-radius:var(--ha-slider-handle-size);background-color:var(--white-color)}
.ha-control-slider--vertical{width:var(--control-slider-thickness,40px);height:100%}
.ha-control-slider--vertical .ha-control-slider__bar{top:auto;bottom:0;transform:translate3d(0,calc((1 - var(--value,0)) * 100%),0)}
.ha-control-slider--vertical.ha-control-slider--handle .ha-control-slider__bar{transform:translate3d(0,calc((1 - var(--value,0)) * (100% - 2 * var(--ha-slider-handle-margin) - var(--ha-slider-handle-size))),0)}
.ha-control-slider--vertical.ha-control-slider--handle .ha-control-slider__bar::after{top:var(--ha-slider-handle-margin);bottom:auto;right:0;left:0;width:50%;height:var(--ha-slider-handle-size)}
.ha-control-slider--vertical .ha-control-slider__tooltip{display:none}
.ha-control-slider__tooltip{position:absolute;bottom:calc(100% + 4px);left:calc(var(--value,0) * 100%);transform:translateX(-50%);padding:0.2em 0.4em;white-space:nowrap;font-size:var(--ha-font-size-m);color:var(--primary-text-color);background-color:var(--clear-background-color);border-radius:var(--ha-border-radius-lg);box-shadow:0 2px 5px rgba(0,0,0,0.2);opacity:0;transition:opacity var(--ha-control-transition),left var(--ha-control-transition);pointer-events:none}
.ha-control-slider:hover .ha-control-slider__tooltip,.ha-control-slider--tooltip-always .ha-control-slider__tooltip{opacity:1}
.ha-control-slider--disabled{opacity:0.5}
.ha-control-slider--disabled .ha-control-slider__track{cursor:not-allowed}

/* ---------- ha-control-circular-slider ---------- */
.ha-control-circular-slider{position:relative;display:block;width:100%;max-width:320px;aspect-ratio:1}
.ha-control-circular-slider svg{display:block;width:100%;height:100%;overflow:visible}
.ha-control-circular-slider__background{fill:none;stroke:var(--control-circular-slider-background);opacity:var(--control-circular-slider-background-opacity);stroke-width:24;stroke-linecap:round}
.ha-control-circular-slider__arc{fill:none;stroke:var(--control-circular-slider-color);stroke-width:24;stroke-linecap:round;transition:stroke var(--ha-control-transition)}
.ha-control-circular-slider__handle{fill:var(--white-color);stroke:var(--control-circular-slider-color);stroke-width:2}
.ha-control-circular-slider__center{position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center;pointer-events:none;text-align:center}
.ha-control-circular-slider__value{font-size:var(--ha-font-size-5xl);font-weight:var(--ha-font-weight-medium);line-height:var(--ha-line-height-condensed);color:var(--primary-text-color)}
.ha-control-circular-slider__unit{font-size:var(--ha-font-size-xl);vertical-align:top;line-height:1}
.ha-control-circular-slider__label{margin-top:var(--ha-space-1);font-size:var(--ha-font-size-m);color:var(--secondary-text-color)}

/* ---------- ha-control-number-buttons ---------- */
.ha-control-number-buttons{position:relative;width:100%;height:var(--feature-height,40px);color:var(--primary-text-color);font-weight:var(--ha-font-weight-medium);-webkit-tap-highlight-color:transparent}
.ha-control-number-buttons__value{position:relative;display:flex;align-items:center;justify-content:center;width:100%;height:100%;box-sizing:border-box;border-radius:var(--control-number-buttons-border-radius,var(--ha-border-radius-md));overflow:hidden;z-index:0;font-size:inherit;color:inherit;user-select:none;outline:none;transition:box-shadow var(--ha-control-transition)}
.ha-control-number-buttons__value::before{content:"";position:absolute;inset:0;background-color:var(--control-number-buttons-background-color,var(--disabled-color));opacity:var(--control-number-buttons-background-opacity,0.2);transition:background-color var(--ha-control-transition),opacity var(--ha-control-transition)}
.ha-control-number-buttons__value:focus-visible{box-shadow:0 0 0 2px var(--control-number-buttons-focus-color,var(--secondary-text-color))}
.ha-control-number-buttons__unit{white-space:pre}
.ha-control-number-buttons__btn{position:absolute;top:0;bottom:0;width:35px;height:100%;padding:0;border:none;background:none;color:inherit;cursor:pointer;outline:none;display:flex;align-items:center;justify-content:center}
.ha-control-number-buttons__btn:disabled{opacity:0.4;pointer-events:none}
.ha-control-number-buttons__btn--minus{left:0}
.ha-control-number-buttons__btn--plus{right:0}

/* ---------- ha-control-select ---------- */
.ha-control-select{position:relative;display:flex;flex-direction:row;box-sizing:border-box;width:100%;height:var(--control-select-thickness,40px);padding:var(--control-select-padding,4px);gap:var(--control-select-padding,4px);border-radius:var(--control-select-border-radius,10px);color:var(--primary-text-color);font-weight:var(--ha-font-weight-medium);user-select:none;-webkit-tap-highlight-color:transparent}
.ha-control-select::before{content:"";position:absolute;inset:0;background:var(--control-select-background,var(--disabled-color));opacity:var(--control-select-background-opacity,0.2);border-radius:var(--control-select-border-radius,10px)}
.ha-control-select__option{position:relative;flex:1;display:flex;align-items:center;justify-content:center;min-width:0;height:100%;padding:0;border:none;background:none;color:inherit;font:inherit;cursor:pointer;outline:none;overflow:hidden;z-index:0;border-radius:calc(var(--control-select-border-radius,10px) - var(--control-select-padding,4px));transition:box-shadow var(--ha-control-transition)}
.ha-control-select__option::before{content:"";position:absolute;inset:0;background-color:var(--control-select-color,var(--primary-color));opacity:0;border-radius:inherit;transition:background-color var(--ha-control-transition),opacity 80ms ease-in-out}
.ha-control-select__option:hover::before{opacity:var(--control-select-focused-opacity,0.2)}
.ha-control-select__option:focus-visible{box-shadow:0 0 0 2px var(--control-select-color,var(--primary-color))}
.ha-control-select__option--selected{color:var(--white-color)}
.ha-control-select__option--selected::before{opacity:1}
.ha-control-select__content{position:relative;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:2px;width:100%;max-height:100%;padding:2px;box-sizing:border-box;text-align:center;pointer-events:none;overflow:hidden}
.ha-control-select__content span{display:block;width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:var(--ha-font-size-s);line-height:1.2}
/* icon + label together needs a taller control than the 40px icon-only default */
.ha-control-select--stacked{height:var(--control-select-stacked-thickness,56px)}
.ha-control-select--vertical{flex-direction:column;width:var(--control-select-thickness,40px);height:auto}
.ha-control-select--disabled{color:var(--disabled-color)}
.ha-control-select--disabled .ha-control-select__option::before{background-color:var(--disabled-color);opacity:0}
.ha-control-select--disabled .ha-control-select__option{cursor:not-allowed}

/* ---------- ha-alert ---------- */
.ha-alert{position:relative;display:flex;padding:var(--ha-space-2);color:var(--primary-text-color)}
.ha-alert::after{content:"";position:absolute;inset:0;opacity:0.12;border-radius:var(--ha-border-radius-sm);pointer-events:none}
.ha-alert__icon{flex:none;height:var(--ha-alert-icon-size,24px);width:var(--ha-alert-icon-size,24px)}
.ha-alert__content{display:flex;justify-content:space-between;align-items:center;width:100%}
.ha-alert__main{margin-inline:var(--ha-space-2);overflow-wrap:anywhere;line-height:normal}
.ha-alert__title{margin-top:2px;font-weight:var(--ha-font-weight-bold)}
.ha-alert__action{z-index:1;width:auto;flex:none}
.ha-alert--info::after{background-color:var(--info-color)}
.ha-alert--info>.ha-alert__icon{color:var(--info-color)}
.ha-alert--warning::after{background-color:var(--warning-color)}
.ha-alert--warning>.ha-alert__icon{color:var(--warning-color)}
.ha-alert--error::after{background-color:var(--error-color)}
.ha-alert--error>.ha-alert__icon{color:var(--error-color)}
.ha-alert--success::after{background-color:var(--success-color)}
.ha-alert--success>.ha-alert__icon{color:var(--success-color)}

/* ---------- ha-badge ---------- */
.ha-badge{position:relative;display:flex;flex-direction:row;align-items:center;justify-content:center;gap:var(--ha-space-2);box-sizing:border-box;height:var(--ha-badge-size,36px);min-width:var(--ha-badge-size,36px);width:auto;padding:0 12px;background:var(--ha-card-background,var(--card-background-color));border:var(--ha-card-border-width,1px) solid var(--ha-card-border-color,var(--divider-color));border-radius:var(--ha-badge-border-radius,calc(var(--ha-badge-size,36px) / 2));box-shadow:var(--ha-card-box-shadow,none);font:inherit;color:var(--primary-text-color);transition:box-shadow var(--ha-control-transition),border-color var(--ha-control-transition)}
.ha-badge--button{cursor:pointer}
.ha-badge--button:hover{background:color-mix(in srgb,var(--badge-color) 4%,var(--card-background-color))}
.ha-badge:focus-visible{outline:none;border-color:var(--badge-color);box-shadow:0 0 0 1px var(--badge-color)}
.ha-badge__icon{display:flex;color:var(--badge-color);line-height:0;margin-inline-start:-4px}
.ha-badge--icon-only{padding:0}
.ha-badge--icon-only .ha-badge__icon{margin-inline-start:0}
.ha-badge__info{display:flex;flex-direction:column;align-items:flex-start;text-align:center}
.ha-badge__label{font-size:var(--ha-font-size-xs);font-weight:var(--ha-font-weight-medium);line-height:10px;letter-spacing:0.1px;color:var(--secondary-text-color)}
.ha-badge__content{font-size:var(--ha-badge-font-size,var(--ha-font-size-s));font-weight:var(--ha-font-weight-medium);line-height:var(--ha-line-height-condensed);letter-spacing:0.1px;color:var(--primary-text-color)}

/* ---------- ha-chip (assist chip) ---------- */
.ha-chip{position:relative;display:inline-flex;align-items:center;gap:var(--ha-space-2);height:32px;padding:0 var(--ha-space-4);box-sizing:border-box;border:1px solid var(--outline-color);border-radius:var(--ha-assist-chip-container-shape,16px);background:transparent;color:var(--primary-text-color);font-family:var(--ha-font-family-body);font-size:var(--ha-font-size-m);font-weight:var(--ha-font-weight-normal);line-height:1;cursor:pointer;transition:background-color var(--ha-control-transition),border-color var(--ha-control-transition)}
.ha-chip:hover{background-color:color-mix(in srgb,var(--primary-text-color) 8%,transparent)}
.ha-chip:focus-visible{outline:none;box-shadow:0 0 0 2px var(--primary-color)}
.ha-chip--filled{border-color:transparent;background-color:var(--ha-assist-chip-filled-container-color)}
.ha-chip--active{border-color:transparent;background-color:var(--ha-assist-chip-active-container-color);color:var(--primary-color)}
.ha-chip--active .ha-chip__icon{color:var(--primary-color)}
.ha-chip:disabled{opacity:0.38;cursor:not-allowed}
.ha-chip__icon{display:flex;flex:none}
.ha-chips{display:flex;flex-wrap:wrap;gap:var(--ha-space-2)}

/* ---------- ha-expansion-panel ---------- */
.ha-expansion-panel{display:block}
.ha-expansion-panel--outlined{border:1px solid var(--outline-color);border-radius:var(--ha-card-border-radius,var(--ha-border-radius-lg))}
.ha-expansion-panel__summary{display:flex;flex:1;align-items:center;gap:var(--ha-space-2);width:100%;min-height:48px;padding:var(--expansion-panel-summary-padding,0 var(--ha-space-2));box-sizing:border-box;border:none;background:none;color:var(--primary-text-color);font-family:var(--ha-font-family-body);font-size:var(--ha-font-size-m);font-weight:var(--ha-font-weight-medium);text-align:start;cursor:pointer;outline:none;border-radius:var(--ha-card-border-radius,var(--ha-border-radius-lg))}
.ha-expansion-panel__summary:focus-visible{background:var(--input-fill-color)}
.ha-expansion-panel__header{flex:1;min-width:0;overflow-wrap:anywhere}
.ha-expansion-panel__secondary{display:block;color:var(--secondary-text-color);font-size:var(--ha-font-size-s);font-weight:var(--ha-font-weight-normal)}
.ha-expansion-panel__chevron{flex:none;color:var(--primary-text-color);transition:transform var(--ha-animation-duration-fast) cubic-bezier(0.4,0,0.2,1)}
.ha-expansion-panel--expanded .ha-expansion-panel__chevron{transform:rotate(180deg)}
.ha-expansion-panel__container{overflow:hidden;height:0;padding:var(--expansion-panel-content-padding,0 var(--ha-space-2));transition:height var(--ha-expansion-transition)}
.ha-expansion-panel--expanded .ha-expansion-panel__container{height:auto;overflow:initial}

/* ---------- ha-gauge / ha-bar ---------- */
.ha-gauge{position:relative;display:block;width:100%}
.ha-gauge__levels-base{fill:none;stroke:var(--primary-background-color);stroke-width:12;stroke-linecap:butt}
.ha-gauge__level{fill:none;stroke-width:12;stroke-linecap:butt}
.ha-gauge__value{fill:none;stroke:var(--gauge-color,var(--primary-color));stroke-width:12;stroke-linecap:butt;transition:stroke-dashoffset 1s ease 0s}
.ha-gauge__needle{fill:var(--primary-text-color);stroke:var(--card-background-color);stroke-width:1;stroke-linecap:round;transform-origin:0 0;transition:all 1s ease 0s}
.ha-gauge__text{position:absolute;left:50%;bottom:6%;transform:translateX(-50%);font-size:var(--ha-font-size-l);color:var(--primary-text-color);text-align:center;white-space:nowrap}
.ha-bar{display:block;width:100%;height:12px;border-radius:var(--ha-bar-border-radius,var(--ha-border-radius-sm));overflow:hidden;background:var(--ha-bar-background-color,var(--secondary-background-color))}
.ha-bar__value{height:100%;background:var(--ha-bar-primary-color,var(--primary-color))}

/* ---------- ha-dialog ---------- */
.ha-dialog-scrim{position:fixed;inset:0;display:flex;align-items:center;justify-content:center;padding:var(--ha-space-4);background:rgba(0,0,0,0.32);backdrop-filter:var(--ha-dialog-scrim-backdrop-filter);z-index:10}
.ha-dialog{display:flex;flex-direction:column;width:100%;min-width:min(400px,100%);max-width:min(600px,95vw);max-height:90vh;background:var(--card-background-color);color:var(--primary-text-color);border-radius:var(--ha-dialog-border-radius,var(--ha-border-radius-4xl));box-shadow:var(--ha-box-shadow-l);overflow:hidden}
.ha-dialog__header{display:flex;align-items:center;gap:var(--ha-space-4);padding:var(--ha-space-3) var(--ha-space-4);min-height:var(--header-height)}
.ha-dialog__title{flex:1;min-width:0;font-size:var(--ha-font-size-xl);font-weight:var(--ha-font-weight-medium);line-height:var(--ha-line-height-condensed)}
.ha-dialog__subtitle{display:block;font-size:var(--ha-font-size-s);font-weight:var(--ha-font-weight-normal);color:var(--secondary-text-color)}
.ha-dialog__content{padding:0 var(--ha-space-6) var(--ha-space-4);overflow-y:auto}
.ha-dialog__footer{display:flex;align-items:center;justify-content:var(--justify-action-buttons,flex-end);gap:var(--ha-space-2);padding:var(--ha-space-3) var(--ha-space-4);border-top:1px solid var(--divider-color)}

/* ---------- add-on tab row (shared by the UI kit and the template) ---------- */
.ha-tab{display:flex;align-items:center;gap:var(--ha-space-2);height:48px;padding:0 var(--ha-space-4);border:none;border-bottom:2px solid transparent;background:none;color:var(--secondary-text-color);font-family:var(--ha-font-family-body);font-size:var(--ha-font-size-m);font-weight:var(--ha-font-weight-medium);cursor:pointer;white-space:nowrap;transition:color var(--ha-control-transition),border-color var(--ha-control-transition)}
.ha-tab:hover{color:var(--primary-text-color)}
.ha-tab--active{color:var(--primary-color);border-bottom-color:var(--primary-color)}
.ha-icon-button{display:flex;align-items:center;justify-content:center;width:var(--min-touch-target);height:var(--min-touch-target);border:none;background:none;border-radius:var(--ha-border-radius-circle);color:var(--sidebar-icon-color);cursor:pointer;transition:background-color var(--ha-control-transition),color var(--ha-control-transition)}
.ha-icon-button:hover{background:var(--ha-color-fill-neutral-quiet-hover);color:var(--primary-text-color)}

/* ---------- ha-icon ---------- */
.ha-icon{display:inline-flex;align-items:center;justify-content:center;flex:none;width:var(--mdc-icon-size,24px);height:var(--mdc-icon-size,24px);fill:currentColor}

/* ---------- text button, used in dialogs and card actions ---------- */
.ha-button{display:inline-flex;align-items:center;justify-content:center;gap:var(--ha-space-2);flex:none;height:var(--ha-space-9);padding:0 var(--ha-space-2);border:none;border-radius:var(--ha-border-radius-sm);background:none;color:var(--primary-color);font-family:var(--ha-font-family-body);font-size:var(--ha-font-size-m);font-weight:var(--ha-font-weight-medium);letter-spacing:0.0892857143em;text-transform:uppercase;white-space:nowrap;cursor:pointer;transition:background-color var(--ha-control-transition)}
.ha-button:hover{background-color:color-mix(in srgb,var(--primary-color) 8%,transparent)}
.ha-button:focus-visible{outline:none;box-shadow:0 0 0 2px var(--primary-color)}
.ha-button--danger{color:var(--error-color)}
.ha-button--danger:hover{background-color:color-mix(in srgb,var(--error-color) 8%,transparent)}
.ha-button:disabled{color:var(--disabled-text-color);cursor:not-allowed;background:none}
`;
