/* Merges the Home Assistant design system into one stylesheet the add-on can
   inline. The mirror under .agent/design-mirror/_ds/ is the source: those files
   came from the design project verbatim, and this module is the only thing that
   edits them. Two edits are made, both because an add-on page must not reach the
   network, and both are named in the output so a reader sees what changed. */

export const SOURCE_ORDER = [
  "tokens/fonts.css",
  "tokens/core-colors.css",
  "tokens/semantic-colors.css",
  "tokens/theme.css",
  "tokens/typography.css",
  "tokens/core.css",
  "tokens/components.css",
  "tokens/elevation.css",
  "components/ha-components.css",
] as const;

/* The upstream body stack asks for two web fonts. Neither is fetched, so the
   substitutes are the ones a Korean reader already has installed: Apple's on
   macOS and iOS, Malgun on Windows, and whatever `system-ui` resolves to
   elsewhere. Roboto and Noto Sans KR stay at the front for the machines that
   happen to have them locally. */
const BODY_STACK =
  'Roboto,"Noto Sans KR","Apple SD Gothic Neo","Malgun Gothic",system-ui,sans-serif';

const NOTE = (what: string): string => `/* removed by tools/design/build-css.ts: ${what} */`;

/** Strips the two network dependencies out of `tokens/fonts.css`. */
export function stripWebFonts(css: string): string {
  return css
    .replace(/^@import url\("https:\/\/fonts\.googleapis\.com[^\n]*\n/m, `${NOTE("the Google Fonts @import — the page makes no external request")}\n`)
    .replace(/^@font-face\{[^\n]*\}\n/m, `${NOTE("the Roboto @font-face — the variable TTF is not shipped with the add-on")}\n`);
}

/** Points the body font at what is already installed rather than at a download. */
export function localiseBodyFont(css: string): string {
  return css.replace(
    /^--ha-font-family-body:[^\n]*$/m,
    `--ha-font-family-body:${BODY_STACK};`,
  );
}

/** Applies the per-file edits. Everything not named here is passed through. */
export function transform(path: string, css: string): string {
  if (path === "tokens/fonts.css") return stripWebFonts(css);
  if (path === "tokens/typography.css") return localiseBodyFont(css);
  return css;
}

/** Merges the nine sheets in @import order, each behind a banner naming its source. */
export function mergeCss(read: (path: string) => string): string {
  return SOURCE_ORDER.map((path) => {
    const body = transform(path, read(path)).trimEnd();
    return `/* ===== _ds/${path} ===== */\n${body}\n`;
  }).join("\n");
}

const HEADER = `// Generated by tools/design/build-css.ts from .agent/design-mirror/_ds/.
// Do not edit by hand: run \`node tools/design/emit.ts\` and commit the result.
// The mirror holds the design project's files verbatim; the two edits made on
// the way here are marked in the CSS itself.
`;

/** Wraps the merged CSS in the TypeScript module the add-on imports. */
export function emitModule(css: string): string {
  if (css.includes("`") || css.includes("${")) {
    throw new Error("merged CSS contains a backtick or a template placeholder");
  }
  return `${HEADER}\nexport const HA_DESIGN_SYSTEM_CSS = String.raw\`\n${css}\`;\n`;
}
